Topic = "message"
Channel = "persist"
LookupdHTTPAddrs = []
NsqdTCPAddrs = ["127.0.0.1:4150"]
MaxInFlight = 200

[MysqlConfigs]
    [MysqlConfigs.write]
    User = "horn"
    Pass = "HornMima1@#"
    Addr = "127.0.0.1:3306"
    Protocol = "tcp"
    Dbname = "horn"

    [MysqlConfigs.read]
    User = "horn"
    Pass = "HornMima1@#"
    Addr = "127.0.0.1:3306"
    Protocol = "tcp"
    Dbname = "horn"